export const demoUsers = {
  student: {
    id: "stu-001",
    role: "student",
    name: "Aarav Mehta",
    email: "student@campus.edu",
    password: "student123",
    detail: "B.Tech CSE · Semester 6",
    initials: "AM",
  },
  faculty: {
    id: "fac-001",
    role: "faculty",
    name: "Dr. Neha Sharma",
    email: "faculty@campus.edu",
    password: "faculty123",
    detail: "Computer Science Department",
    initials: "NS",
  },
  admin: {
    id: "adm-001",
    role: "admin",
    name: "Rohan Kapoor",
    email: "admin@campus.edu",
    password: "admin123",
    detail: "Campus Administration",
    initials: "RK",
  },
};

export const defaultState = {
  notices: [
    {
      id: "notice-001",
      title: "WebNova 2026 Project Submission",
      summary:
        "All shortlisted teams must submit the final presentation, source code repository, deployed link, and a two-minute demo video.",
      department: "Innovation Cell",
      type: "Submission",
      priority: "High",
      published: "29 May 2026",
      deadline: "6 Jun 2026",
      deadlineISO: "2026-06-06",
      action: "Submit PPT, GitHub link, deployed URL, and demo video.",
      source: "Circular #04 · WebNova 2026",
      audience: "All Students",
      verified: true,
      views: 842,
      saved: 316,
      createdBy: "Campus Administration",
    },
    {
      id: "notice-002",
      title: "End Semester Examination Registration",
      summary:
        "Examination forms for the Spring 2026 end semester examinations are open on the student portal.",
      department: "Examination Cell",
      type: "Academic",
      priority: "High",
      published: "1 Jun 2026",
      deadline: "10 Jun 2026",
      deadlineISO: "2026-06-10",
      action: "Complete the examination form and verify registered subjects.",
      source: "Exam Cell Notice #18",
      audience: "All Students",
      verified: true,
      views: 1234,
      saved: 629,
      createdBy: "Examination Cell",
    },
    {
      id: "notice-003",
      title: "AI and Responsible Innovation Seminar",
      summary:
        "A guest seminar exploring responsible AI development, product ethics, and career pathways.",
      department: "Computer Science",
      type: "Event",
      priority: "Medium",
      published: "2 Jun 2026",
      deadline: "8 Jun 2026",
      deadlineISO: "2026-06-08",
      action: "Register using the campus events portal.",
      source: "CSE Department Memo #22",
      audience: "CSE Students",
      verified: true,
      views: 468,
      saved: 201,
      createdBy: "Dr. Neha Sharma",
    },
    {
      id: "notice-004",
      title: "Library Timing Extended During Exams",
      summary:
        "The central library will remain open until midnight on weekdays during examination preparation week.",
      department: "Library",
      type: "General",
      priority: "Low",
      published: "3 Jun 2026",
      deadline: "20 Jun 2026",
      deadlineISO: "2026-06-20",
      action: "Carry a valid college ID for entry after 8 PM.",
      source: "Library Circular #09",
      audience: "Everyone",
      verified: true,
      views: 687,
      saved: 97,
      createdBy: "Campus Administration",
    },
  ],
  tasks: [
    {
      id: "task-001",
      title: "Submit WebNova 2026 project",
      detail: "PPT, source code, deployed link, and demo video",
      due: "6 Jun",
      dueISO: "2026-06-06",
      priority: "High",
      complete: false,
      source: "Circular #04 · WebNova 2026",
    },
    {
      id: "task-002",
      title: "Register for AI seminar",
      detail: "Computer Science auditorium · 11:00 AM",
      due: "8 Jun",
      dueISO: "2026-06-08",
      priority: "Medium",
      complete: false,
      source: "CSE Department Memo #22",
    },
    {
      id: "task-003",
      title: "Complete examination form",
      detail: "Verify registered subjects before submission",
      due: "10 Jun",
      dueISO: "2026-06-10",
      priority: "High",
      complete: false,
      source: "Exam Cell Notice #18",
    },
    {
      id: "task-004",
      title: "Upload internship preference form",
      detail: "Placement cell summer internship preferences",
      due: "14 Jun",
      dueISO: "2026-06-14",
      priority: "Low",
      complete: true,
      source: "Placement Cell Update #06",
    },
  ],
  events: [
    {
      id: "event-001",
      title: "AI and Responsible Innovation",
      category: "Seminar",
      department: "Computer Science",
      date: "8 Jun 2026",
      time: "11:00 AM",
      place: "CSE Auditorium",
      seats: 42,
      registered: false,
      color: "violet",
    },
    {
      id: "event-002",
      title: "Startup Pitching Bootcamp",
      category: "Workshop",
      department: "Innovation Cell",
      date: "11 Jun 2026",
      time: "2:00 PM",
      place: "Incubation Centre",
      seats: 18,
      registered: true,
      color: "coral",
    },
    {
      id: "event-003",
      title: "Inter-College Basketball Trials",
      category: "Sports",
      department: "Student Affairs",
      date: "13 Jun 2026",
      time: "6:30 AM",
      place: "Main Sports Ground",
      seats: 25,
      registered: false,
      color: "blue",
    },
    {
      id: "event-004",
      title: "Alumni Career Conversations",
      category: "Career",
      department: "Placement Cell",
      date: "17 Jun 2026",
      time: "4:00 PM",
      place: "Online",
      seats: 120,
      registered: false,
      color: "green",
    },
  ],
  questions: [
    {
      id: "question-001",
      student: "Ishita Rao",
      initials: "IR",
      question: "Can second-year students register for the AI seminar?",
      course: "CSE Department",
      asked: "12 min ago",
      status: "Open",
      answer: "",
    },
    {
      id: "question-002",
      student: "Kabir Singh",
      initials: "KS",
      question: "Is a deployed link compulsory for the WebNova submission?",
      course: "Innovation Cell",
      asked: "36 min ago",
      status: "Open",
      answer: "",
    },
    {
      id: "question-003",
      student: "Riya Jain",
      initials: "RJ",
      question: "Will the database systems lab be open this Friday?",
      course: "Database Systems",
      asked: "1 hr ago",
      status: "Answered",
      answer: "Yes, the lab will be open from 10 AM to 4 PM.",
    },
  ],
  complaints: [
    {
      id: "complaint-001",
      title: "Projector not working in C-204",
      category: "Infrastructure",
      submittedBy: "Aarav Mehta",
      submitted: "3 Jun 2026",
      status: "In progress",
      detail: "The projector disconnects every few minutes during lectures.",
    },
    {
      id: "complaint-002",
      title: "Wi-Fi coverage near library",
      category: "IT Services",
      submittedBy: "Ishita Rao",
      submitted: "2 Jun 2026",
      status: "Open",
      detail: "The Wi-Fi connection drops frequently on the second floor.",
    },
    {
      id: "complaint-003",
      title: "Water cooler maintenance",
      category: "Facilities",
      submittedBy: "Kabir Singh",
      submitted: "1 Jun 2026",
      status: "Resolved",
      detail: "The water cooler outside Block B needed servicing.",
    },
  ],
  lostFound: [
    {
      id: "lost-001",
      item: "Black scientific calculator",
      type: "Lost",
      place: "Library second floor",
      date: "3 Jun 2026",
      contact: "Aarav Mehta",
      status: "Open",
    },
    {
      id: "lost-002",
      item: "Blue college ID card",
      type: "Found",
      place: "CSE Lab 3",
      date: "2 Jun 2026",
      contact: "Lab Assistant",
      status: "Open",
    },
  ],
  users: [
    {
      id: "user-001",
      name: "Aarav Mehta",
      email: "student@campus.edu",
      role: "Student",
      department: "Computer Science",
      status: "Active",
      lastSeen: "Today, 9:42 AM",
    },
    {
      id: "user-002",
      name: "Ishita Rao",
      email: "ishita@campus.edu",
      role: "Student",
      department: "Electronics",
      status: "Active",
      lastSeen: "Today, 9:18 AM",
    },
    {
      id: "user-003",
      name: "Dr. Neha Sharma",
      email: "faculty@campus.edu",
      role: "Faculty",
      department: "Computer Science",
      status: "Active",
      lastSeen: "Today, 8:56 AM",
    },
    {
      id: "user-004",
      name: "Prof. Arjun Sethi",
      email: "arjun@campus.edu",
      role: "Faculty",
      department: "Electronics",
      status: "Active",
      lastSeen: "Yesterday, 6:22 PM",
    },
    {
      id: "user-005",
      name: "Rohan Kapoor",
      email: "admin@campus.edu",
      role: "Admin",
      department: "Administration",
      status: "Active",
      lastSeen: "Today, 9:50 AM",
    },
    {
      id: "user-006",
      name: "Ananya Bose",
      email: "ananya@campus.edu",
      role: "Student",
      department: "Business Studies",
      status: "Suspended",
      lastSeen: "28 May 2026",
    },
  ],
  activity: [
    {
      id: "activity-001",
      title: "New verified notice published",
      detail: "End Semester Examination Registration",
      time: "22 min ago",
      tone: "blue",
    },
    {
      id: "activity-002",
      title: "Student question answered",
      detail: "Database Systems lab timing",
      time: "1 hr ago",
      tone: "green",
    },
    {
      id: "activity-003",
      title: "Complaint moved to in progress",
      detail: "Projector not working in C-204",
      time: "3 hrs ago",
      tone: "coral",
    },
    {
      id: "activity-004",
      title: "Event registration crossed 100",
      detail: "Alumni Career Conversations",
      time: "Yesterday",
      tone: "violet",
    },
  ],
};

export const navByRole = {
  teacher: [
    ["overview", "Overview", "home"],
    ["publish", "Publish update", "plus"],
    ["notices", "My notices", "notice"],
    ["questions", "Student questions", "chat"],
    ["classes", "Classes", "calendar"],
    ["insights", "Insights", "chart"],
  ],
  student: [
    ["overview", "Overview", "home"],
    ["notices", "Notice hub", "notice"],
    ["assistant", "AI assistant", "spark"],
    ["deadlines", "Deadlines", "calendar"],
    ["events", "Events", "event"],
    ["support", "Campus support", "support"],
  ],
  faculty: [
    ["overview", "Overview", "home"],
    ["publish", "Publish update", "plus"],
    ["notices", "My notices", "notice"],
    ["questions", "Student questions", "chat"],
    ["classes", "Classes", "calendar"],
    ["insights", "Insights", "chart"],
  ],
  admin: [
    ["overview", "Overview", "home"],
    ["notice-center", "Notice center", "upload"],
    ["users", "Users & roles", "users"],
    ["moderation", "Requests", "support"],
    ["analytics", "Analytics", "chart"],
  ],
};

export const pageLabels = {
  overview: "Overview",
  notices: "Notice hub",
  assistant: "AI query assistant",
  deadlines: "Deadline tracker",
  events: "Campus events",
  support: "Campus support",
  publish: "Publish an update",
  questions: "Student questions",
  classes: "Classes and schedule",
  insights: "Faculty insights",
  "notice-center": "Notice center",
  users: "Users and roles",
  moderation: "Campus requests",
  analytics: "Platform analytics",
};
